# Correct and Complete config.yml

# --- Global Settings ---
debug: false

messages:
  # The prefix for most plugin messages.
  prefix: "&c&l[Christmas]&r "

  # Message shown when a player earns shards from breaking a block or killing a mob
  shards-earned: "&a+ %amount% shards &7(You now have %total%)"

  # Message shown when a player doesn't have enough shards for a purchase
  not-enough-shards: "&cNot enough shards!"

  # Message shown when a player successfully buys an item
  bought-item: "&aPurchase successful! New balance: %balance% shards"


# --- Feature Toggles ---
# Use these settings to quickly enable or disable major features.

toggles:
  # Enables the shard economy (earning shards from blocks/mobs, shard manager).
  shard-economy: true
  
  # Enables the /shards shop command and the GUI itself.
  shard-shop: true
  
  # Enables the daily gift item and the daily gift manager.
  daily-gifts: true
  
  # Enables the Santa NPC spawning and interaction logic.
  santa-event: true
  
  # Enables the /playchristmas command and the music manager.
  music: true
  
  # Enables the ability to earn rewards by hitting villagers with snowballs.
  villager-snowball: true


# ❄ Snow effect settings
snow:
  enabled: true
  apply-to-all-players: true        # auto-enable for everyone online
  keep-snow-on-disable: true        # keep thin layers when a player disables the effect
  radius: 24                        # horizontal radius around the player
  density: 40                       # particle burst per tick slice (visual only)
  duration: 0                       # 0 = infinite (seconds per player)
  no-snow-near-player-radius: 1.5   # safe ring around feet
  no-snow-near-entity-radius: 1.25  # avoid placing near interactables/Santa

  presnow:
    bias-front: true
    lookahead-factor: 0.66          # 0.0..2.0 how much to bias ahead

  # Ground placement rules
  respect-roof: true                # no ground snow if player under a ceiling
  blocked-wg-regions:               # particles still show here; only ground snow is blocked
    - santa_zone
    # - market
    # - spawn
