# Correct and Complete config.yml

# --- Global Settings ---
debug: false

messages:
  # The prefix for most plugin messages.
  prefix: "&c&l[Christmas]&r "

  # Message shown when a player earns shards from breaking a block or killing a mob
  shards-earned: "&a+ %amount% shards &7(You now have %total%)"

  # Message shown when a player doesn't have enough shards for a purchase
  not-enough-shards: "&cNot enough shards!"

  # Message shown when a player successfully buys an item
  bought-item: "&aPurchase successful! New balance: %balance% shards"


# --- Feature Toggles ---
# Use these settings to quickly enable or disable major features.

toggles:
  # Enables the shard economy (earning shards from blocks/mobs, shard manager).
  shard-economy: true
  
  # Enables the /shards shop command and the GUI itself.
  shard-shop: true
  
  # Enables the daily gift item and the daily gift manager.
  daily-gifts: true
  
  # Enables the Santa NPC spawning and interaction logic.
  santa-event: true
  
  # Enables the /playchristmas command and the music manager.
  music: true
  
  # Enables the ability to earn rewards by hitting villagers with snowballs.
  villager-snowball: true


# ❄ Snow effect settings
snow:
  enabled: true                 # auto-enable snow for everyone on startup
  apply-to-all-players: true    # apply to current & future joins (unless they opt out)
  radius: 6                     # horizontal radius of effect around each player
  duration: 0                   # seconds per player; 0 = infinite
  density: 40                   # particle intensity (visual only)

  # Cleanup behavior when a player disables the effect (/snowify):
  keep-snow-on-disable: true    # if false, thin snow near them is removed

  # Prevent snow right where players click or near interactables (Santa, frames, etc.)
  no-snow-near-player-radius: 1.5
  no-snow-near-entity-radius: 1.25

  # Make the world look snowy *ahead* of the player instead of only underfoot
  presnow:
    bias-front: true            # prefer placing snow in front of the player
    lookahead-factor: 0.66      # portion of radius to nudge forward (0.0–2.0)
