name: UltimateChristmas
version: '1.0-SNAPSHOT'
main: fr.elias.ultimateChristmas.UltimateChristmas
api-version: '1.21'
depend: [NoteBlockAPI]
softdepend: [WorldGuard, LibsDisguises, ProtocolLib]
loadbefore: [LuckPerms]
authors: [Elias]

commands:
  shards:
    description: Shard balance / shop / admin give
    usage: "/shards [shop|give|set]"
    permission: ultimatechristmas.shards

  snowify:
    description: Toggle a gentle snow effect around you
    usage: "/snowify [on|off]"
    permission: ultimatechristmas.snow.use

  playchristmas:
    description: Play a configured .nbs track
    usage: "/playchristmas <trackKey>|stop|list"
    permission: ultimatechristmas.music.play

  santaadmin:
    description: Admin commands for the Santa NPC
    usage: "/santaadmin <spawn|despawn|reload>"
    permission: ultimatechristmas.admin

  ucgift:
    description: Daily gift commands
    usage: "/ucgift give <player>"
    permission: ultimatechristmas.gift.give

  advent:
    description: Open or manage the Advent Calendar
    aliases: [calendar, adventcalendar]
    usage: "/advent [open|claim|remaining|streak|help] [player]"
    permission: ultimatechristmas.advent.use

  grinchboss:
    description: Manage the Grinch boss (spawn/despawn/setspawn/status)
    usage: "/grinchboss <spawn|despawn|setspawn|status>"
    permission: ultimatechristmas.grinch.admin

permissions:
  ultimatechristmas.admin:
    description: Grants access to all UltimateChristmas admin commands
    default: op

  # Shards
  ultimatechristmas.shards:
    description: Use /shards base command (balance, etc.)
    default: true
  ultimatechristmas.shop.use:
    description: Open the shard shop GUI
    default: true

  # Music
  ultimatechristmas.music.play:
    description: Allows using /playchristmas
    default: op

  # Snow effect toggle
  ultimatechristmas.snow.use:
    description: Allows /snowify
    default: true

  # Snowball / villager rewards
  ultimatechristmas.snowball.reward:
    description: Allows players to earn rewards for snowball hits
    default: true

  # Daily gift / advent
  ultimatechristmas.gift.give:
    description: Allows /ucgift give <player>
    default: op
  ultimatechristmas.advent.use:
    description: Use Advent Calendar commands (/advent)
    default: true
  ultimatechristmas.advent.admin:
    description: Manage others’ calendar claims / view streaks
    default: op

  # Grinch boss
  ultimatechristmas.grinch.admin:
    description: Allows /grinchboss admin commands
    default: op
