name: UltimateChristmas
version: '1.0-SNAPSHOT'
main: fr.elias.ultimateChristmas.UltimateChristmas
api-version: '1.21'
depend: [NoteBlockAPI]
loadbefore: [LuckPerms, LibsDisguises]
authors: [Elias]


commands:
  shards:
    description: Shard balance / shop / admin give
    usage: "/shards [shop|give|set]"
    permission: ultimatechristmas.shards
  snowify:
    description: Toggles a gentle snow effect around you
  playchristmas:
    description: Play a configured .nbs track
    usage: "/playchristmas <trackKey>|stop|list"
    permission: ultimatechristmas.music.play

  santaadmin:
    description: Admin commands for the Santa NPC.
    usage: "/santaadmin <spawn|despawn|reload>"
    permission: ultimatechristmas.admin

  ucgift:
    description: Daily gift commands
    usage: "/ucgift give <player>"
    permission: ultimatechristmas.gift.give

  advent:
    description: Open or manage the Advent Calendar
    aliases: [calendar, adventcalendar]
    usage: "/advent [open|claim|remaining|streak|help] [player]"
    permission: ultimatechristmas.advent.use

permissions:
  ultimatechristmas.admin:
    description: Grants access to all UltimateChristmas admin commands.
    default: op

  # Shards
  ultimatechristmas.shards:
    description: Use /shards base command (balance, etc.)
    default: true
  ultimatechristmas.shop.use:
    description: Open the shard shop GUI.
    default: true

  # Music
  ultimatechristmas.music.play:
    description: Allows using /playchristmas
    default: op

  # Snowball / villager rewards
  ultimatechristmas.snowball.reward:
    description: Allows players to earn rewards for snowball hits.
    default: true

  # Daily gift / advent
  ultimatechristmas.gift.give:
    description: Allows /ucgift give <player>.
    default: op
  ultimatechristmas.advent.use:
    description: Use Advent Calendar commands (/advent).
    default: true
  ultimatechristmas.advent.admin:
    description: Manage others’ calendar claims / view streaks.
    default: op
